feat: add button
nerdbord/nerdux-ui-system pull request #32
Opened 2023-04-05 21:21 UTC by wawrzonnn

2023-04-06 11:47 UTC, Sumick requested changes
Few things to fix

2023-04-06 11:47 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +		<button className={allClasses} type={type} disabled={disabled}>
**nitpick:** As you are more experienced dev now, I have to stick to missing formatting. Look how hard to read that when you don't use any formatter in your code

2023-04-06 11:47 UTC, Sumick commented on src/inputs/Button/Button.stories.tsx
> +		<div className={styles.button__container}>
**issue:** It definitely should not look like that. First of all, `icon` should be a prop. You Button with icon should look like following: 

```javascript
<Button isLoading={false} icon={<Plus />} variant={'primary'} {...args} onClick={() => console.log('clicked')}/>
```

2023-04-06 11:47 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +		<button className={allClasses} type={type} disabled={disabled}>
oh, this is open source - so it should format your code here. Please add prettier formatting to `husky` file.

2023-04-06 19:48 UTC, Sumick requested changes
- [ ] Remove `package-lock.json`
- [ ] Refactor class names to use `cx` like in other components
- [ ] Fix formatting (it's still not properly formatted)

2023-04-06 19:48 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +	const disabledClass = disabled ? (variant === 'primary' ? styles.disabledPrimary : styles.disabledSecondary) : ''
**issue:** We are using `cx` for joining classes - check how its done in `TextField`

2023-04-06 19:48 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +	console.log(calculateDefaultDimensions(16, 50));
**nitpick:** Remove log

2023-04-06 19:48 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +					{children}
**nitpick:** This is still not formated

2023-04-07 10:46 UTC, Sumick requested changes
- [ ] Remove redundant files (including `package-lock.json`)
- [ ] Fix component props interface
- [ ] Fix formatting for CSS

2023-04-07 10:46 UTC, Sumick commented on git reset --hard a0251b6c32f3167b7eb4a59fefb6067893ca7ca6
> +[33mcommit 212692e65b07a0f8fef88b4350b982ba1df48701[m[33m ([m[1;36mHEAD -> [m[1;32mmain[m[33m)[m
**nitpick**: We should delete this file

2023-04-07 10:46 UTC, Sumick commented on src/inputs/Button/Button.module.css
> +.secondary:hover {
**nitpick:** CSS is missing formatting here

2023-04-07 10:46 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +  children: React.ReactNode;
**nitpick:** We should not define children this way. Use `PropsWitchChildren<ButtonProps>` instead

2023-04-07 16:56 UTC, Sumick requested changes
Almost there!

2023-04-07 16:56 UTC, Sumick commented on src/icons/Plus.tsx
> +export const calculateDefaultDimensions = (x: number, scale = 100) => {
**nitpick:** This method should be somewhere else - maybe create `helpers.ts` file in `icons` directory, and put it there

2023-04-07 16:56 UTC, Sumick commented on src/inputs/Button/Button.stories.tsx
> +    icon={<Plus />}
**nitpick:** This icon looks definitely too big. Let's scale it down. + It does not look properly without icon (text is not centered):

<img width="364" alt="Zrzut ekranu 2023-04-7 o 18 51 27" src="https://user-images.githubusercontent.com/22893188/230646706-43ca3245-e826-4c4f-8b21-a72173e67d7c.png">

2023-04-07 16:56 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +    isLoadingPrimary: variant === "primary" && isLoading && !disabled,
**nitpick:** You duplicate these variant values - it's worth to move the to some `const` or `enum`, like:

`
enum ButtonVariant {
 primary = 'primary'
 ...
}
`

2023-04-07 16:56 UTC, Sumick commented on src/inputs/Button/Button.tsx
> +    <button className={buttonClasses} type={type} disabled={disabled}>
**issue**: `isLoading` looks, and behaves different than on design. It should not have hover, and box shadow

<img width="653" alt="Zrzut ekranu 2023-04-7 o 18 54 31" src="https://user-images.githubusercontent.com/22893188/230647140-cd75fc09-3bf4-4557-830b-4587e0932c09.png">

2023-04-11 20:23 UTC, NerdbordMentor requested changes
### Feedback
The code changes made in the previous messages are correct and meet the task requirements. However, there are some improvements that can be made to make the code more efficient and readable.

#### Improvements
- In `.husky/pre-commit` file, it is recommended to add comments explaining what each command does.
- In `src/icons/Plus.tsx` file, it is recommended to add a comment explaining what the `scaleCalculation` function does.
- In `src/inputs/Button/Button.module.css` file, it is recommended to remove unused CSS styles.
- In `src/inputs/Button/Button.stories.tsx` file, it is recommended to remove the `variant: "primary"` property from the `Default.args` object since it is already defined in the `<Button>` component.
- In `src/inputs/Button/Button.tsx` file, it is recommended to remove the duplicate declaration of `type`, `isLoading`, `variant`, `icon`, and `children`.
- It is also recommended to add comments explaining what each prop does in the `<Button>` component.

#### Task list
- [ ] Add comments explaining what each command does in `.husky/pre-commit`.
- [ ] Add a comment explaining what the `scaleCalculation` function does in `src/icons/Plus.tsx`.
- [ ] Remove unused CSS styles in `src/inputs/Button/Button.module.css`.
- [ ] Remove the `variant: "primary"` property from the `Default.args` object in `src/inputs/Button/Button.stories.tsx`.
- [ ] Remove duplicate declaration of props in `<Button>` component in

2023-04-11 20:28 UTC, NerdbordMentor approved these changes
### Feedback
The code changes made in the previous messages are correct and meet the task requirements. However, there are some improvements that can be made to make the code more efficient and readable.

#### Improvements
- In `.husky/pre-commit` file, it is recommended to add comments explaining what each command does.
- In `src/icons/Plus.tsx` file, it is recommended to add a comment explaining what the `scaleCalculation` function does.
- In `src/inputs/Button/Button.module.css` file, it is recommended to remove unused CSS styles.
- In `src/inputs/Button/Button.stories.tsx` file, it is recommended to remove the unnecessary `variant: "primary"` property from the `Default.args`.
- In `src/inputs/Button/Button.tsx` file, it is recommended to remove the unused import of `Fragment`.

#### Task List
- [ ] Add comments explaining what each command does in `.husky/pre-commit` file.
- [ ] Add a comment explaining what the `scaleCalculation` function does in `src/icons/Plus.tsx` file.
- [ ] Remove unused CSS styles in `src/inputs/Button/Button.module.css` file.
- [ ] Remove unnecessary `variant: "primary"` property from the `Default.args` in `src/inputs/Button/Button.stories.tsx` file.
- [ ] Remove unused import of `Fragment` in

2023-04-11 21:13 UTC, NerdbordMentor approved these changes
### Feedback
After reviewing the code changes, here is my feedback:
- The changes made to `.husky/pre-commit` file seem correct and meet the task requirements.
- The changes made to `src/icons/Plus.tsx` file seem correct and meet the task requirements.
- The changes made to `src/icons/scaleCalculation.ts` file seem correct and meet the task requirements.
- The changes made to `src/inputs/Button/Button.module.css` file seem correct and meet the task requirements.
- The changes made to `src/inputs/Button/Button.stories.tsx` file seem correct and meet the task requirements.
- The changes made to `src/inputs/Button/Button.tsx` file seem correct and meet the task requirements. However, there are some improvements that can be made:
  - [ ] Add a default value for the `variant` prop in case it is not provided by the user.
  - [ ] Remove redundant comments such as `// eslint-disable-next-line react/jsx-no-bind`.
  - [ ] Use destructuring assignment for props in function arguments instead of using `PropsWithChildren`.
  - [ ] Move the type definition of `ButtonProps` outside of the component function for better readability.
  - [ ] Use consistent naming conventions for CSS classes (e.g. use kebab-case instead of camelCase).
  
Overall, good job on implementing the Button component!

2023-04-16 13:56 UTC, Sumick approved these changes
Looks good!

2023-04-16 13:56 UTC, merged