Button test
nerdbord/nerdux-ui-system pull request #33
Opened 2023-04-05 21:59 UTC by wawrzonnn

2023-04-06 12:20 UTC, Sumick requested changes
We need to fix button first on your previous PR - you should also remove package-lock.json, as we already have `yarn.lock`. Keeping these two together can lead to packages incompatibilities. We should decide on one

2023-04-06 12:20 UTC, Sumick commented on src/inputs/Button/Button.module.css
> +	background: #b23386;
**nitpick:** We have to start thinking about CSS variables to stop duplicating these values

2023-04-06 12:20 UTC, Sumick commented on src/inputs/Button/Button.stories.tsx
> +    <div className={styles.button__container}>
**issue:** We need to fix this button first

2023-04-17 13:01 UTC, NerdbordMentor approved these changes
## Code Review

### Button.module.css
- In `.buttons`, `min-width` should be `minWidth` for consistency with other CSS properties.
- In `.primary:hover`, `background` and `box-shadow` should be combined into a single `box-shadow` property for better readability.
- In `.secondary`, `background` should be removed since it is already set to white in `.button__container`.
- In `.secondary:hover`, `filter` should be removed since it is not needed.
- In `.disabledPrimary:hover`, `border` should be removed since it is already set to transparent in `.disabledPrimary`.
- In `.loadingPrimary`, `box-shadow` should be removed since it is not needed.
- In `.loadingSecondary`, `box-shadow` should be removed since it is not needed.
- In `.iconSettings` and `.iconSpinner`, `display: flex` should be removed since it is not needed.
- In `.iconSpinnerRotate`, `animation-duration` should be added to specify the duration of the animation.

### Button.tsx
- The `type` prop should have a default value of `"button"`.
- The `isLoading` prop should have a default value of `false`.
- The `onClick` prop should have a type of `(event: React.MouseEvent<HTMLButtonElement>) => void`.
- The `variant` prop should have a default value of `"primary"`.
- The `children` prop should have a type of `React.ReactNode`.
- The `getDisabledClassForSpecificVariant` function is not needed and can be removed.
- The `dynamicClasses` variable can be renamed to `allClasses`.
- The `globalButtonClass`, `variantClass`, `disabledClass`, and `loadingClass` variables can be combined into a single `allClasses` variable for better readability.
- The `handleClick` function can be simplified by checking if the button is not disabled and not loading before calling the `onClick` prop.
- The `Spinner` component should have a `data-testid` prop for testing purposes.

### Button.stories.tsx
- The `Button` component should be renamed to `Default` to avoid naming conflicts with the `Button` module.
- The `Button` component should have a `type` prop set to `"button"`.
- The `Button` component should have an `isLoading` prop set to `false`.
- The `Icon` story should be added to test the rendering of an icon with the button.
- The `MultiTextField` story should be renamed to `Default` to avoid naming conflicts with the `TextField` module.
- The `TextField` component import should be formatted for consistency.

### TextField.stories.tsx
- The `TextField` component import should be formatted for consistency.

### Overall
- The code changes satisfy the requirements of the task.
- The changes to `Button.module.css` improve readability and remove unnecessary code.
- The changes to `Button.tsx` simplify the code and improve readability.
- The changes to `Button.stories.tsx` add additional tests and improve consistency.
- The changes to `TextField.stories.tsx` improve consistency.
- The code changes are well-formatted and easy to read.
- No bugs were found in the code changes.
- Best practices were followed in the code changes.

2023-04-17 13:27 UTC, Sumick approved these changes

2023-04-17 13:33 UTC, merged